[font]
normal = {family = "Iosevka", style = "regular"}

[window]
opacity = 0.8

[colors.normal]
black   = "#595959"
red     = "#ff71ad"
green   = "#56d6a0"
yellow  = "#fdfa3f"
blue    = "#3eddf2"
magenta = "#fc209f"
cyan    = "#44ece4"
white   = "#e4e4e4"

[colors.bright]
black   = "#676767"
red     = "#fa3866"
green   = "#56d6a0"
yellow  = "#fdfa3f"
blue    = "#00e1ff"
magenta = "#ff0086"
cyan    = "#00fff2"
white   = "#f9f9f9"


[mouse]
bindings = [
    {mouse = "Right", mods = "Control", action = "Paste"},
    {mouse = "Middle", mods = "Control", action = "Copy"},
]
